name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate light theme SVG
      - name: Generate light snake SVG
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: jackwinkler2
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: dist/github-contribution-grid-snake.svg

      # Generate dark theme SVG
      - name: Generate dark snake SVG
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: jackwinkler2
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # List files in dist directory
      - name: List files in dist directory
        run: ls -l dist || echo "dist folder or files missing"

      # Push to output branch
      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
