name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake SVG
        uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: jackwinkler2
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: dist/github-contribution-grid-snake.svg
          
      - name: Fix background color in SVG
        run: |
          sed -i 's/#ffffff/#161b22/g' dist/github-contribution-grid-snake.svg
          sed -i 's/#fff/#161b22/g' dist/github-contribution-grid-snake.svg

      - name: List files in dist
        run: ls -l dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

